apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-opyqpsrp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-opyqpsrp:ccd52ee23de78c7d635f4016070c209503ae28b7@sha256:6e804c6a1e95e5bee658c326cc4a862d3754dcc6546f45d731c24c575dd4c4de
          name: container-image
